### ISSUE TITLE
Create electron app for hyperdrive-daemon

### ISSUE THREAD

**Issue by juliangruber** [libscie/hyperdaemon#1]
As discussed in the calls with hyperdivision, we want to prototype a little electron menu bar app that hosts https://github.com/andrewosh/hyperdrive-daemon, and uses https://github.com/andrewosh/hyperdrive-daemon-client to connect to it.

This will help us get familiar with the project, and serve as a simple one-click installer for the daemon.

In my mind this would be a small hack project, that goes over 3-5 days, and can be done after the Hypergraph Desktop demo on Tuesday March 31st.

Some features to include:

- monitoring
- start / stop
- installer
- auto updates

cc @jameslibscie

**Comment by jameslibscie** [comment]
Sounds good! @juliangruber :)
