### ISSUE TITLE
Sanity check on performance

### ISSUE THREAD

**Issue by jameslibscie** [libscie/hyperdaemon#26]
Since this is completely new, I'd like to do a quick "sanity check" on the performance of the Daemon app.

To me, this entails:
- [x] Checking up on CPU, RAM, disk and network usage while the Daemon is running and transferring files
- [x] Sharing findings with the team
- [ ] Having a chat regarding performance testing in general

**Comment by juliangruber** [comment]
Thank you for taking the initiative and prioritizing this <3

**Comment by jameslibscie** [comment]
Great! Perhaps a quick test with a module containing a 1 GB-ish file? And one containing 1000 small files?

**Comment by juliangruber** [comment]
Blocked by https://github.com/hypercore-protocol/hyperdrive-daemon/issues/79

**Comment by juliangruber** [comment]
While transferring a 500MB file from my iMac to my Macbook Air, on the Air the CPU usage never went above 15%, and this was during a Zoom call (which itself uses 40% CPU). After transferring, memory is at a stable 106MB, so no memory leaks hopefully.

I wouldn't be surprised if Dropbox used similar amounts of resources.

**Comment by jameslibscie** [comment]
Nice! That sounds similar to Dropbox indeed. Especially when lots of files have been changed, Dropbox can get heavy. Let's do some more tests further down the line.

**Comment by jameslibscie** [comment]
I've made a note to talk about performance testing during the next dev call, as I'd like to develop some kind of strategy for this still. Closing this issue though :)
