### ISSUE TITLE
View Daemon status

### ISSUE THREAD

**Issue by jameslibscie** [libscie/hyperdaemon#3]
**User story**
As a content creator
I want my profile and content to continuously synchronize to the network
so that my work is more available and more quickly updated

**Acceptance criteria**
- [x] While the Daemon is running, a system tray icon is displayed
- [x] The system tray icons allows the user to close the Daemon
- [x] Hovering over the system tray icon displays whether the Daemon is running correctly or not

**Comment by juliangruber** [comment]
This has been implemented for a while :)
