### ISSUE TITLE
graphical assets

### ISSUE THREAD

**Issue by juliangruber** [libscie/hyperdaemon#5]
We're going to need these assets for release:

- [x] app icon (`512x512.png` or larger)
- [x] menu bar icons (`19x19.png`, `@2x.png`, `@4x.png`)
  - [x] white on black
    - [x] daemon on
    - [x] daemon off
  - [x] black on white
    - [x] daemon on
    - [x] daemon off
- [x] DMG background

No windows `.ico` is necessary for now, but it wouldn't harm either.

**Comment by psobrakseaton** [comment]
The assets can be found [here](https://www.figma.com/file/3XizYy2b3leCkTozF44R9P/hyperdrive-daemon-assets). The icon is supposed to be reminiscent of a rocket tail or wormhole. The shape is really simple so it can work at the 19x19.

**Comment by juliangruber** [comment]
These look so cool! How do you envision the three supplied colors _white_, _black_ and _punch_ map to the states I laid out above?

**Comment by juliangruber** [comment]
ico: https://libscie.slack.com/files/UQU8PLD1D/F012YPJJDK3/hyperdrive-icon.ico

**Comment by juliangruber** [comment]
<img width="528" alt="Screenshot 2020-04-28 at 16 17 48" src="https://user-images.githubusercontent.com/10247/80498274-d23de880-896b-11ea-9b5c-ddc06d3299d9.png">

<img width="444" alt="Screenshot 2020-04-28 at 16 18 05" src="https://user-images.githubusercontent.com/10247/80498363-ebdf3000-896b-11ea-99cf-af33c46e2ccd.png">

<img width="458" alt="Screenshot 2020-04-28 at 16 18 11" src="https://user-images.githubusercontent.com/10247/80498328-dff36e00-896b-11ea-839a-bde3a8292ee3.png">
